//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// このソース コードは xsd によって自動生成されました。Version=4.8.3928.0 です。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Toukaitetudou.ExtendedTrainScheduler.Config")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="Toukaitetudou.ExtendedTrainScheduler.Config", IsNullable=false)]
public partial class ExtendedTrainSchedulerWithOudiaConfig {
    
    private Config configField;
    
    private Operation[] operationField;
    
    /// <remarks/>
    public Config Config {
        get {
            return this.configField;
        }
        set {
            this.configField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Operation")]
    public Operation[] Operation {
        get {
            return this.operationField;
        }
        set {
            this.operationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="Toukaitetudou.ExtendedTrainScheduler.Config")]
public partial class Config {
    
    private bool realTimeUpdateField;
    
    private bool updateOutputFileField;
    
    private Bound vehicleDirectionField;
    
    private string vehicleOperationNumberField;
    
    private string oud2FilePathField;
    
    private string timeTableNameField;
    
    public Config() {
        this.realTimeUpdateField = true;
        this.updateOutputFileField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool RealTimeUpdate {
        get {
            return this.realTimeUpdateField;
        }
        set {
            this.realTimeUpdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool UpdateOutputFile {
        get {
            return this.updateOutputFileField;
        }
        set {
            this.updateOutputFileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public Bound VehicleDirection {
        get {
            return this.vehicleDirectionField;
        }
        set {
            this.vehicleDirectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string VehicleOperationNumber {
        get {
            return this.vehicleOperationNumberField;
        }
        set {
            this.vehicleOperationNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Oud2FilePath {
        get {
            return this.oud2FilePathField;
        }
        set {
            this.oud2FilePathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string TimeTableName {
        get {
            return this.timeTableNameField;
        }
        set {
            this.timeTableNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="Toukaitetudou.ExtendedTrainScheduler.Config")]
public enum Bound {
    
    /// <remarks/>
    InBound,
    
    /// <remarks/>
    OutBound,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="Toukaitetudou.ExtendedTrainScheduler.Config")]
public partial class Operation {
    
    private string operationNumberField;
    
    private string inBoundTrainFilePathField;
    
    private string outBoundTrainFilepathField;
    
    private string seriesField;
    
    private string carsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string OperationNumber {
        get {
            return this.operationNumberField;
        }
        set {
            this.operationNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string InBoundTrainFilePath {
        get {
            return this.inBoundTrainFilePathField;
        }
        set {
            this.inBoundTrainFilePathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string OutBoundTrainFilepath {
        get {
            return this.outBoundTrainFilepathField;
        }
        set {
            this.outBoundTrainFilepathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string Series {
        get {
            return this.seriesField;
        }
        set {
            this.seriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Cars {
        get {
            return this.carsField;
        }
        set {
            this.carsField = value;
        }
    }
}
