//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtendedTrainSchedulerWithOudia.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExtendedTrainSchedulerWithOudia {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExtendedTrainSchedulerWithOudia() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtendedTrainSchedulerWithOudia.Resources.ExtendedTrainSchedulerWithOudia", typeof(ExtendedTrainSchedulerWithOudia).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The Operation Number is Duplicate. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OperationNumberDuplication {
            get {
                return ResourceManager.GetString("OperationNumberDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Operation Number is not Defined. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OperationNumberNotDefined {
            get {
                return ResourceManager.GetString("OperationNumberNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The version of the oud2 file is not appropriate. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OudFileFormat {
            get {
                return ResourceManager.GetString("OudFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The oud2 file is not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OudFileIsNotFound {
            get {
                return ResourceManager.GetString("OudFileIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The format of the schema of script plugin package manifest XML is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlSchemaValidation {
            get {
                return ResourceManager.GetString("XmlSchemaValidation", resourceCulture);
            }
        }
    }
}
